# Base image
FROM node:10  

RUN mkdir -p /app

COPY . /app

# RUN apt-get update && apt-get install -y dnsutils iputils-ping curl

# Set working directory
WORKDIR /app


# Install the Angular CLI globally
RUN npm install -g @angular/cli@6.0.0

# Install app dependencies
RUN npm install

# Expose port 4200 for the Angular app
EXPOSE 4200

ENTRYPOINT ["tail", "-f", "/dev/null"]

